### ISSUE TITLE
<flvis/KeyFrame.h> is missing

### ISSUE THREAD

**Issue by antithing** [Ttoto/FLVIS#14]
Hi, and thank you for making this code available. I am trying to build it, and it looks like 

KeyFrame.h
CorrectionInf.h

are missing. Should these headers be included? Where can i find them?

Thanks!

**Comment by Ttoto** [comment]
Hi，these two files will be generated when u compile with catkin_make. It will be geneated from msg files.

**Comment by antithing** [comment]
Ah I see. I am trying to remove the ROS dependency and run this code on Windows, is there any way you could attach these two .h files here? It would be very much appreciated!

Thank you.

**Comment by JazzyFeng** [comment]
Hi, [antithing](https://github.com/antithing). Thanks for your question. I attach header file Keyframe.h and CorrectionInf.h below for your reference.  You could copy and paste them in windows.
`// Generated by gencpp from file flvis/KeyFrame.msg
// DO NOT EDIT!


#ifndef FLVIS_MESSAGE_KEYFRAME_H
#define FLVIS_MESSAGE_KEYFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <std_msgs/Int64MultiArray.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <std_msgs/UInt8MultiArray.h>
#include <geometry_msgs/Transform.h>

namespace flvis
{
template <class ContainerAllocator>
struct KeyFrame_
{
  typedef KeyFrame_<ContainerAllocator> Type;

  KeyFrame_()
    : header()
    , frame_id(0)
    , command(0)
    , img0()
    , img1()
    , lm_count(0)
    , lm_id_data()
    , lm_2d_data()
    , lm_3d_data()
    , lm_descriptor_data()
    , T_c_w()  {
    }
  KeyFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frame_id(0)
    , command(0)
    , img0(_alloc)
    , img1(_alloc)
    , lm_count(0)
    , lm_id_data(_alloc)
    , lm_2d_data(_alloc)
    , lm_3d_data(_alloc)
    , lm_descriptor_data(_alloc)
    , T_c_w(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _frame_id_type;
  _frame_id_type frame_id;

   typedef int8_t _command_type;
  _command_type command;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img0_type;
  _img0_type img0;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img1_type;
  _img1_type img1;

   typedef int32_t _lm_count_type;
  _lm_count_type lm_count;

   typedef  ::std_msgs::Int64MultiArray_<ContainerAllocator>  _lm_id_data_type;
  _lm_id_data_type lm_id_data;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _lm_2d_data_type;
  _lm_2d_data_type lm_2d_data;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _lm_3d_data_type;
  _lm_3d_data_type lm_3d_data;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _lm_descriptor_data_type;
  _lm_descriptor_data_type lm_descriptor_data;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _T_c_w_type;
  _T_c_w_type T_c_w;





  typedef boost::shared_ptr< ::flvis::KeyFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flvis::KeyFrame_<ContainerAllocator> const> ConstPtr;

}; // struct KeyFrame_

typedef ::flvis::KeyFrame_<std::allocator<void> > KeyFrame;

typedef boost::shared_ptr< ::flvis::KeyFrame > KeyFramePtr;
typedef boost::shared_ptr< ::flvis::KeyFrame const> KeyFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flvis::KeyFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flvis::KeyFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flvis::KeyFrame_<ContainerAllocator1> & lhs, const ::flvis::KeyFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frame_id == rhs.frame_id &&
    lhs.command == rhs.command &&
    lhs.img0 == rhs.img0 &&
    lhs.img1 == rhs.img1 &&
    lhs.lm_count == rhs.lm_count &&
    lhs.lm_id_data == rhs.lm_id_data &&
    lhs.lm_2d_data == rhs.lm_2d_data &&
    lhs.lm_3d_data == rhs.lm_3d_data &&
    lhs.lm_descriptor_data == rhs.lm_descriptor_data &&
    lhs.T_c_w == rhs.T_c_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flvis::KeyFrame_<ContainerAllocator1> & lhs, const ::flvis::KeyFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flvis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::flvis::KeyFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flvis::KeyFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flvis::KeyFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flvis::KeyFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flvis::KeyFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flvis::KeyFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flvis::KeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b6e5c7741910e70703abf423a09594e";
  }

  static const char* value(const ::flvis::KeyFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b6e5c7741910e70ULL;
  static const uint64_t static_value2 = 0x703abf423a09594eULL;
};

template<class ContainerAllocator>
struct DataType< ::flvis::KeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flvis/KeyFrame";
  }

  static const char* value(const ::flvis::KeyFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flvis::KeyFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int64  frame_id\n"
"int8   command\n"
"sensor_msgs/Image img0\n"
"sensor_msgs/Image img1\n"
"int32 lm_count\n"
"std_msgs/Int64MultiArray lm_id_data\n"
"geometry_msgs/Vector3[]  lm_2d_data\n"
"geometry_msgs/Vector3[]  lm_3d_data\n"
"std_msgs/UInt8MultiArray lm_descriptor_data\n"
"geometry_msgs/Transform  T_c_w\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int64[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: std_msgs/UInt8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint8[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::flvis::KeyFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flvis::KeyFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frame_id);
      stream.next(m.command);
      stream.next(m.img0);
      stream.next(m.img1);
      stream.next(m.lm_count);
      stream.next(m.lm_id_data);
      stream.next(m.lm_2d_data);
      stream.next(m.lm_3d_data);
      stream.next(m.lm_descriptor_data);
      stream.next(m.T_c_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flvis::KeyFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flvis::KeyFrame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frame_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.frame_id);
    s << indent << "command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command);
    s << indent << "img0: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img0);
    s << indent << "img1: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img1);
    s << indent << "lm_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lm_count);
    s << indent << "lm_id_data: ";
    s << std::endl;
    Printer< ::std_msgs::Int64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.lm_id_data);
    s << indent << "lm_2d_data[]" << std::endl;
    for (size_t i = 0; i < v.lm_2d_data.size(); ++i)
    {
      s << indent << "  lm_2d_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.lm_2d_data[i]);
    }
    s << indent << "lm_3d_data[]" << std::endl;
    for (size_t i = 0; i < v.lm_3d_data.size(); ++i)
    {
      s << indent << "  lm_3d_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.lm_3d_data[i]);
    }
    s << indent << "lm_descriptor_data: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.lm_descriptor_data);
    s << indent << "T_c_w: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.T_c_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLVIS_MESSAGE_KEYFRAME_H`

CorrectionInf.h
`// Generated by gencpp from file flvis/CorrectionInf.msg
// DO NOT EDIT!


#ifndef FLVIS_MESSAGE_CORRECTIONINF_H
#define FLVIS_MESSAGE_CORRECTIONINF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Transform.h>
#include <std_msgs/Int64MultiArray.h>
#include <geometry_msgs/Vector3.h>
#include <std_msgs/Int64MultiArray.h>

namespace flvis
{
template <class ContainerAllocator>
struct CorrectionInf_
{
  typedef CorrectionInf_<ContainerAllocator> Type;

  CorrectionInf_()
    : frame_id(0)
    , T_c_w()
    , lm_count(0)
    , lm_id_data()
    , lm_3d_data()
    , lm_outlier_count(0)
    , lm_outlier_id_data()  {
    }
  CorrectionInf_(const ContainerAllocator& _alloc)
    : frame_id(0)
    , T_c_w(_alloc)
    , lm_count(0)
    , lm_id_data(_alloc)
    , lm_3d_data(_alloc)
    , lm_outlier_count(0)
    , lm_outlier_id_data(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _frame_id_type;
  _frame_id_type frame_id;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _T_c_w_type;
  _T_c_w_type T_c_w;

   typedef int32_t _lm_count_type;
  _lm_count_type lm_count;

   typedef  ::std_msgs::Int64MultiArray_<ContainerAllocator>  _lm_id_data_type;
  _lm_id_data_type lm_id_data;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _lm_3d_data_type;
  _lm_3d_data_type lm_3d_data;

   typedef int32_t _lm_outlier_count_type;
  _lm_outlier_count_type lm_outlier_count;

   typedef  ::std_msgs::Int64MultiArray_<ContainerAllocator>  _lm_outlier_id_data_type;
  _lm_outlier_id_data_type lm_outlier_id_data;





  typedef boost::shared_ptr< ::flvis::CorrectionInf_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flvis::CorrectionInf_<ContainerAllocator> const> ConstPtr;

}; // struct CorrectionInf_

typedef ::flvis::CorrectionInf_<std::allocator<void> > CorrectionInf;

typedef boost::shared_ptr< ::flvis::CorrectionInf > CorrectionInfPtr;
typedef boost::shared_ptr< ::flvis::CorrectionInf const> CorrectionInfConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flvis::CorrectionInf_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flvis::CorrectionInf_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flvis::CorrectionInf_<ContainerAllocator1> & lhs, const ::flvis::CorrectionInf_<ContainerAllocator2> & rhs)
{
  return lhs.frame_id == rhs.frame_id &&
    lhs.T_c_w == rhs.T_c_w &&
    lhs.lm_count == rhs.lm_count &&
    lhs.lm_id_data == rhs.lm_id_data &&
    lhs.lm_3d_data == rhs.lm_3d_data &&
    lhs.lm_outlier_count == rhs.lm_outlier_count &&
    lhs.lm_outlier_id_data == rhs.lm_outlier_id_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flvis::CorrectionInf_<ContainerAllocator1> & lhs, const ::flvis::CorrectionInf_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flvis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::flvis::CorrectionInf_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flvis::CorrectionInf_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flvis::CorrectionInf_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flvis::CorrectionInf_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flvis::CorrectionInf_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flvis::CorrectionInf_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flvis::CorrectionInf_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69b5519673cbe3c8b9c018e46213bff9";
  }

  static const char* value(const ::flvis::CorrectionInf_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69b5519673cbe3c8ULL;
  static const uint64_t static_value2 = 0xb9c018e46213bff9ULL;
};

template<class ContainerAllocator>
struct DataType< ::flvis::CorrectionInf_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flvis/CorrectionInf";
  }

  static const char* value(const ::flvis::CorrectionInf_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flvis::CorrectionInf_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64                    frame_id\n"
"geometry_msgs/Transform  T_c_w\n"
"int32                    lm_count\n"
"std_msgs/Int64MultiArray lm_id_data\n"
"geometry_msgs/Vector3[]  lm_3d_data\n"
"int32                    lm_outlier_count\n"
"std_msgs/Int64MultiArray lm_outlier_id_data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int64[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::flvis::CorrectionInf_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flvis::CorrectionInf_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame_id);
      stream.next(m.T_c_w);
      stream.next(m.lm_count);
      stream.next(m.lm_id_data);
      stream.next(m.lm_3d_data);
      stream.next(m.lm_outlier_count);
      stream.next(m.lm_outlier_id_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CorrectionInf_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flvis::CorrectionInf_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flvis::CorrectionInf_<ContainerAllocator>& v)
  {
    s << indent << "frame_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.frame_id);
    s << indent << "T_c_w: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.T_c_w);
    s << indent << "lm_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lm_count);
    s << indent << "lm_id_data: ";
    s << std::endl;
    Printer< ::std_msgs::Int64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.lm_id_data);
    s << indent << "lm_3d_data[]" << std::endl;
    for (size_t i = 0; i < v.lm_3d_data.size(); ++i)
    {
      s << indent << "  lm_3d_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.lm_3d_data[i]);
    }
    s << indent << "lm_outlier_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lm_outlier_count);
    s << indent << "lm_outlier_id_data: ";
    s << std::endl;
    Printer< ::std_msgs::Int64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.lm_outlier_id_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLVIS_MESSAGE_CORRECTIONINF_H`

**Comment by JazzyFeng** [comment]
> 
Hi,  @[antithing](https://github.com/antithing) Thanks for your question. I attach a compressed file, which includes codes of header file Keyframe.h and CorrectionInf.h below, for your reference. You could uncompress, copy and paste them.
[header.zip](https://github.com/HKPolyU-UAV/FLVIS/files/8899289/header.zip)

**Comment by antithing** [comment]
Thank you very much! I am trying to remove the ROS dependency from this code. This will be very helpful.

Quick question, looking through this, it seems like just the types that are ros specific, and the data input handling will need to be changed to remove ros from the code. Does this seem right?

Do you know of any reason why I would not be able to remove ros?

Thanks!
